### ISSUE TITLE
Simple problem

### ISSUE THREAD

**Issue by noahaus** [tgvaughan/MASTER#48]
Hello Tim,

I feel like a complete idiot for not knowing how to get MASTER to do one simulation run, but even with following the tutorials on the wiki I receive errors.

The problem is related to BEAST saying that the json output doesn't exist.

Here is the BEAST 2 Error: 

```
Random number seed: 1566239839471

Assembling model...
Setting up populations... done.
Setting up reactions... Birth... Death... done.
Model assembled.

Error 110 parsing the xml input file

validate and intialize error: File StochasticLogistic_out.json not found.

Error detected about here:
  <beast>
      <run spec='Trajectory'>
          <output spec='JsonOutput'>

java.lang.RuntimeException: File StochasticLogistic_out.json not found.
	at master.outputs.JsonOutput.initAndValidate(Unknown Source)
	at beast.util.XMLParser.initBEASTObjects(Unknown Source)
	at beast.util.XMLParser.parse(Unknown Source)
	at beast.util.XMLParser.parseFile(Unknown Source)
	at beast.app.BeastMCMC.parseArgs(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
```

And here is the XML I give to BEAST 2: 

```
<beast version='2.0' namespace='master:master.model:master.steppers:master.conditions:master.postprocessors:master.outputs'>
    <run spec='Trajectory'
         simulationTime='20'
         verbosity='1'>

        <model spec='Model' id='model'>
            <population spec='Population' populationName="X" id='X'/>
            <reaction spec='Reaction' reactionName="Birth" rate="1.0">
                X -> 2X
            </reaction>
            <reaction spec='Reaction' reactionName="Death" rate="0.01">
                2X -> X
            </reaction>
        </model>

        <initialState spec='InitState'>
            <populationSize spec='PopulationSize' population="@X" size='1'/>
        </initialState>

        <output spec='JsonOutput' fileName='StochasticLogistic_out.json'/>
    </run>
</beast> 
```

Any help would be greatly appreciated.

**Comment by tgvaughan** [comment]
Hi Noah, don't feel bad - these sorts of errors are confusing.  I just tried running this XML on BEAST 2.6 on MacOS and no problems occurred, so I don't think the problem is with your XML.  From the error you received it sounds like BEAST can't create the output file (I know it's a strange way to report it, but when Java can't create a file it sometimes throws a "file not found" exception.) 

Is it possible that you didn't have write access to the current working directory? You could try replacing the filename "StochasticLogistic_out.json" with an absolute path to a file in a directory you can definitely write to.

**Comment by noahaus** [comment]
Thank you, adding the absolute path name did the trick! Closing the Issue now.
